import { Inter } from 'next/font/google'

export const metadata = {
    title: 'Phrase',
    description: 'Generated by create next app',
}
const inter = Inter({ subsets: ['latin'] })

export default function PhraseLayout({ children }) {
    return (
        <html lang="en">
            <body className={inter.className}>{children}</body>
        </html>
    )
}
